### ISSUE TITLE
SOURCE OF TRUTH FOR OFNL/API-BACKEND CODEBASE MANAGEMENT/WORKFLOW

### ISSUE THREAD

**Issue by Faithful1** [OFNL-DEV/api-backend#1]
### SOURCE OF TRUTH FOR OFNL/API-BACKEND CODEBASE MANAGEMENT/WORKFLOW

So the idea is to have two major branches named
● dev linked to an staging environment and will be the default branch
● master linked to an production environment

**Staging e.g (https://staging.ofnlapi.com) & Production e.g (https://api.ofnl.com).**
We will have our staging be an exact replica of our production environment.

## Master Branch
The master branch is the production-ready version of our codebase which is automatically
deployed to our production environment (https://api.ofnl.com), with our application fully
tested and code review - certified. “This is a branch that should never be touched”

##Dev Branch
The dev branch is where all feature branches are merged after pull requests have been
thoroughly checked, fixed, and all tests are performed. Once all builds pass, this branch is
deployed to the staging environment (https://staging.ofnlapi.com) for QA & UATs.

## Release Branch
Once it’s time for a release, a release branch should be created from the dev branch for final
audit eg: cleanup & remove comments, versioning etc. This branch is tagged, and then
merged to both master & dev branches.

## Access Control
All code changes to the dev branch will be made via a pull request, and to help prevent
accidental direct pushes, we will use branch permissions. 

### Microservices Architecture

- We will use one repo for one module
- This will cater for separation of concerns
- Easy collaboration
- Avoid conflict and wrongly pushing to a folder/service
- Easy workspace maintenance in the long run

**Comment by Oluadepe** [comment]
@Faithful1 Thank you for the layout which is lovely though I have a question. 1.  Are we just going to create branch and setup a server for that  separate from the master branch server?

**Comment by Faithful1** [comment]
@Oluadepe so ideally each of the branches like so 

-  dev branch will point to staging server (staging.ofnlapi.com)
-  master branch will point to production server (https://api.ofnl.com)

Which means we will only currently be building on staging.ofnlapi.com and this includes whatever we have now.
Nothing is on production yet until we have built to a level where we are fine with what we have.

So even now if you want to show anyone what is going on say investors or any one at all in the planet, you use only staging.ofnlapi.com - thats where we will have the alpha before mvp 

When we have successfully implemented integration of all microservices then we will deploy to production -> Now it is at this point we can say we have a complete MVP say Beta version of the api.

We will set up production when the time comes. For now we work with one server alone and thats staging.

**Comment by Oluadepe** [comment]
Thanks for the detailed explanation. The next step is for us to setup the staging server right? is it on aws or hosting account?

**Comment by Faithful1** [comment]
@Oluadepe That will be an ec2 instance which will spin up the containers using docker-compose.
At this point i am baking the existing api into containers then we can look into getting an instance up with the baked api on ec2. Ideal for development for now. - plus wouldnt cost us anything if we are using the freetier.

**Comment by Oluadepe** [comment]
Good work then. Let the work begins.
